### ISSUE TITLE
cmd window auto closes

### ISSUE THREAD

**Issue by Webby7866** [nortxort/nortbot#27] opened 2019-05-22 03:11 UTC
i set up config and then when  i open the cmd window it auto closes

**Comment by Webby7866** [comment] 2019-05-22 03:16
] [ERROR] '<type 'exceptions.AttributeError'>' 'NoneType' object has no attribute 'connected'

**Comment by nortxort** [comment] 2019-05-22 13:38
I will consider this invalid, until you provide more information.

**Comment by Webby7866** [comment] 2019-05-22 14:20
https://i.imgur.com/DGrpc4s.png

**Comment by Autotonic** [comment] 2019-05-23 08:59
1. The disconnect is related to #24
2. One reconnect the captcha was required
3. If the captcha is required we close the connection
4. So you need to complete the captcha

Granted, the way this disconnects needs to be handled with a bit more grace.

**Comment by Autotonic** [comment] 2019-05-23 15:55
> Granted, the way this disconnects needs to be handled with a bit more grace.

Looks like the error is from within websocket-client, I don't really see anywhere else in tinychat.py that would cause this. 

> If the captcha is required (and anti-captcha api key is not present) we close the connection

Might be worth adding an additional message with something along the lines of "Please complete the captcha using this account and retry.", so the end users know this is expected behavior.
After the [site key](https://github.com/nortxort/nortbot/blob/master/tinychat.py#L672) posted.

**Comment by Webby7866** [comment] 2019-05-24 04:46
How much does this anti captcha cost? i seen something about it but im unaware on it

**Comment by Webby7866** [comment] 2019-05-24 09:01
and how would i go about making !8ball,!Roll and all public so non mods can also use them ?

**Comment by Autotonic** [comment] 2019-05-24 10:41
That's completely up to you to sort out.

**Comment by Webby7866** [comment] 2019-05-28 07:45
is there a line  i can add to ban all users who post a tinychat url? i did !bs *tinychat.com dont seem to work well even tho thats what the commands file says to do

**Comment by Autotonic** [comment] 2019-05-28 11:23
does it ban them then they come right back

**Comment by Webby7866** [comment] 2019-05-28 20:09
no it just lets them post the link and dont even kick them

**Comment by Webby7866** [comment] 2019-05-28 20:09
does nothing

**Comment by Autotonic** [comment] 2019-05-28 21:41
Moving this to #37

**Comment by gloriousone** [comment] 2019-05-28 22:18
With most current version using !bs *tinychat.com does work for me however it only kicks it doesn't ban, no setting to change this within config or bot commands, haven't looked around the code to see where this could be changed manually.

**Comment by Autotonic** [comment] 2019-05-28 22:48
@gloriousone https://github.com/nortxort/nortbot/blob/master/config.ini#L31

**Comment by Autotonic** [comment] 2019-05-28 23:02
@Webby7866 string bans work for me aswell, so i'm thinking this is user error more so than an issue with the bot. If you get an error (a traceback) fill out an [issue request](https://github.com/nortxort/nortbot/blob/master/ISSUE_TEMPLATE.md) and open a new issue.

**Closed by Autotonic** 2019-05-28 23:02 UTC
Labels: invalid

**Comment by Webby7866** [comment] 2019-05-29 15:35
https://i.imgur.com/mqTc9jc.png here is the string file
