### ISSUE TITLE
Error writing unicode to file

### ISSUE THREAD

**Issue by imtammer** [nortxort/nortbot#23] opened 2019-05-10 18:00 UTC
[17:56:48:414] [SYSTEM]: YouTube: CannaBot started "Astrix @ Ozora 2017 - Turn O                                                                                            
n, Tune In, Drop Out"                                                                                                                                                       
[17:56:54:412] MiXed_lag_mute: On phone it’s shit anyways                                                                                                                   
Exception in thread Thread-21:                                                                                                                                              
Traceback (most recent call last):                                                                                                                                          
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner                                                                                              
    self.run()                                                                                                                                                              
  File "/usr/local/lib/python2.7/threading.py", line 754, in run                                                                                                            
    self.__target(*self.__args, **self.__kwargs)                                                                                                                            
  File "/nortbot/tinychat.py", line 163, in connect                                                                                                      
    self._listener()                                                                                                                                                        
  File "/nortbot/tinychat.py", line 212, in _listener                                                                                                    
    self.dispatch(event, json_data)                                                                                                                                         
  File "/nortbot/tinychat.py", line 223, in dispatch                                                                                                     
    self._process_event(event, method, event_data)                                                                                                                          
  File "/nortbot/tinychat.py", line 216, in _process_event                                                                                               
    pe.process()                                                                                                                                                            
  File "/nortbot/_process_event.py", line 71, in process                                                                                                 
    self._process_msg()                                                                                                                                                     
  File "/nortbot/_process_event.py", line 138, in _process_ms                                                                                            
g                                                                                                                                                                           
    self._client.run_method(self._method, *(user, msg))                                                                                                                     
  File "/nortbot/tinychat.py", line 233, in run_method                                                                                                   
    func(*args, **kwargs)                                                                                                                                                   
  File "/nortbot/bot.py", line 163, in on_msg                                                                                                            
    mh.console()                                                                                                                                                            
  File "/nortbot/handlers/message.py", line 57, in console                                                                                               
    self._bot.console.write(msg, Color.B_GREEN)                                                                                                                             
  File "/nortbot/util/console.py", line 154, in write                                                                                                    
    ChatLogger.write_chat_log('%s%s' % (time_stamp, text))                                                                                                                  
  File "/nortbot/util/console.py", line 104, in write_chat_lo                                                                                            
g                                                                                                                                                                           
    text.encode(encoding='UTF-8', errors='ignore'))                                                                                                                         
  File "/nortbot/util/file_handler.py", line 74, in writer                                                                                               
    f.write(write_this + '\n')                                                                                                                                              
  File "/usr/local/lib/python2.7/codecs.py", line 708, in write                                                                                                             
    return self.writer.write(data)                                                                                                                                          
  File "/usr/local/lib/python2.7/codecs.py", line 369, in write                                                                                                             
    data, consumed = self.encode(object, self.errors)                                                                                                                       
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal                                                                                            
 not in range(128)

**Comment by Technetium1** [comment] 2019-05-10 21:39
@Autotonic Unicode is not playing nice https://github.com/nortxort/nortbot/blame/7eb7a883009b3858cf525b0e2fb894986fc4ef76/util/file_handler.py#L73

**Comment by Technetium1** [comment] 2019-05-10 23:21
The issue is that the system locale was `c.utf8`, switching to `en_us.utf8` solved it.

**Comment by imtammer** [comment] 2019-05-11 18:19
ok ive made the change to the handler file check.py as per Aida's instructions changing traceback from 40000 to 10000000, also changed the container environment language to EN.UTF-8 and still got a crash when someone loaded up a bjork video, i believe it to be the umlaut over the o in the title.

**Comment by imtammer** [comment] 2019-05-11 18:19
[18:16:09:824] [SYSTEM]: YouTube: CannaBot started "björk: tabula rasa"                                                                                                      
Exception in thread Thread-21:                                                                                                                                                
Traceback (most recent call last):                                                                                                                                            
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner                                                                                                
    self.run()                                                                                                                                                                
  File "/usr/local/lib/python2.7/threading.py", line 754, in run                                                                                                              
    self.__target(*self.__args, **self.__kwargs)                                                                                                                              
  File "/filestore/CannaBot/nortbot/tinychat.py", line 163, in connect                                                                                                        
    self._listener()                                                                                                                                                          
  File "/filestore/CannaBot/nortbot/tinychat.py", line 212, in _listener                                                                                                      
    self.dispatch(event, json_data)                                                                                                                                           
  File "/filestore/CannaBot/nortbot/tinychat.py", line 223, in dispatch                                                                                                       
    self._process_event(event, method, event_data)                                                                                                                            
  File "/filestore/CannaBot/nortbot/tinychat.py", line 216, in _process_event                                                                                                 
    pe.process()                                                                                                                                                              
  File "/filestore/CannaBot/nortbot/_process_event.py", line 104, in process                                                                                                  
    self._client.run_method(self._method, self._event_data)                                                                                                                   
  File "/filestore/CannaBot/nortbot/tinychat.py", line 233, in run_method                                                                                                     
    func(*args, **kwargs)                                                                                                                                                     
  File "/filestore/CannaBot/nortbot/tinychat.py", line 541, in on_sysmsg                                                                                                      
    self.console.write('[SYSTEM]: %s' % text, Color.WHITE)                                                                                                                    
  File "/filestore/CannaBot/nortbot/util/console.py", line 154, in write                                                                                                      
    ChatLogger.write_chat_log('%s%s' % (time_stamp, text))                                                                                                                    
  File "/filestore/CannaBot/nortbot/util/console.py", line 104, in write_chat_lo                                                                                              
g                                                                                                                                                                             
    text.encode(encoding='UTF-8', errors='ignore'))                                                                                                                           
  File "/filestore/CannaBot/nortbot/util/file_handler.py", line 74, in writer                                                                                                 
    f.write(write_this + '\n')                                                                                                                                                
  File "/usr/local/lib/python2.7/codecs.py", line 708, in write                                                                                                               
    return self.writer.write(data)                                                                                                                                            
  File "/usr/local/lib/python2.7/codecs.py", line 369, in write                                                                                                               
    data, consumed = self.encode(object, self.errors)                                                                                                                         
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 54: ordinal                                                                                              
 not in range(128)

**Comment by Autotonic** [comment] 2019-05-11 21:11
That timer change was to prevent the both from randomly banning users. The fix for this is https://github.com/nortxort/nortbot/commit/9ed828ff9bdd23200a17a19b1b6b24ef5db2eead

**Comment by imtammer** [comment] 2019-05-12 16:21
so far so good with that change to console.py ty for that, will monitor it today see how it goes

**Closed** 2019-05-12 16:56 UTC
